server:
  port: 5900

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        #git地址
        git:
          uri: https://github.com/blppz/config-center.git/
      #git分支
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-7901:7901/eureka/
