server:
  port: 80

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    gateway:
#      routes:
#      - filters:
#        - StripPrefix=1
#        id: nacos-route
#        predicates:
#        - args[pattern]: /nacos/**
#          name: Path
#        uri: lb://consumer-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

# 配置输出日志
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
