server:
  port: 80
spring:
  application:
    name: zuul
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
  #采样比例1
  sleuth:
    sampler:
      rate: 1
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7901:7901/eureka/

consumer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

management:
  endpoint:
    health:
      show-details: always
      enabled: true
    routes:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
