server:
  port: 8900
spring:
  application:
    name: provider
  boot:
    admin:
      client:
        url: http://localhost:6010/
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
  #采样比例1
  sleuth:
    sampler:
      rate: 1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-7901:7901/eureka/

# 如果需要监控当前服务，需要暴露监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"