server:
  port: 8902

spring:
  application:
    name: provider
  boot:
    admin:
      client:
        url: http://localhost:6010/
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
  #采样比例1
  sleuth:
    sampler:
      rate: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/

# 如果需要监控当前服务，需要暴露监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"