server:
  port: 7900

spring:
  application:
    name: eureka-server
  boot:
    admin:
      client:
        url: http://localhost:6010/

eureka:
  server:
    #关闭自我保护
    enable-self-preservation: false
    #缩短清理间隔时间
    eviction-interval-timer-in-ms: 5000
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: false
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: false
    service-url:
      #设置服务注册中心的URL，用于client和server端交流
      defaultZone: http://localhost:7900/eureka/

# 如果需要监控当前服务，需要暴露监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"