server:
  port: 8802

spring:
  application:
    name: consumer
  boot:
    admin:
      client:
        url: http://localhost:6010/
  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #采样比例1
  sleuth:
    sampler:
      rate: 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/

# 修改 Ribbon 负载策略，provider 为具体服务的服务名
provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 启用 hystrix
feign:
  hystrix:
    enabled: true

# 如果需要监控当前服务，需要暴露监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
